### ISSUE TITLE
Disabling "Auto focus search box" currently has no effect

### ISSUE THREAD

**Issue by beaniemonk** [Dubwise56/Dubs-Mint-Menus#2]
Since the latest update, untoggling this option has no effect for me -- the cursor still focuses on the search box whenever I open the architect menu. I tried "Reset All" before untoggling this option, and enabling and disabling again. There's nothing in the log to indicate an error.

This inadvertently types in the search box instead of moving the camera when using the WASD keys with the menu open, and requires build icons to be clicked twice to select. Thanks!

**Comment by Dubwise56** [comment]
fixed in next update
