### ISSUE TITLE
Missing null-check for mods not setting label/names correctly causes NullReferenceException in Search

### ISSUE THREAD

**Issue by tobi1449** [Dubwise56/Dubs-Mint-Menus#3]
Some mods are not setting the label properties for their ThingDefs correctly and since you don't check the labels for null, this causes the bills menu to disappear when using the search.

To fix this, change in Patch_BillStack_DoListing.parc the following lines
`if (p.label.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))`
to
`if (p.label != null && p.label.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))`
  
and
  
`if (p.modContentPack.Name.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))`
to
`if (p.modContentPack != null && p.modContentPack.Name != null && p.modContentPack.Name.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))`
  
and
  
`					if (producedThingDef.label.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))
`
to 
`					if (producedThingDef.label != null && producedThingDef.label.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))`

**Comment by MadaraUchiha** [comment]
Alternatively, just

```cs
if (p?.label.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))
// and
if (p?.modContentPack?.Name.Contains(Patch_BillStack_DoListing.searchString, StringComparison.OrdinalIgnoreCase))
```

**Comment by Dubwise56** [comment]
Fixed in next update
