### ISSUE TITLE
Using Dubs Mint Menus with Change Research Speed breaks save loading

### ISSUE THREAD

**Issue by Gazzoo-byte** [Dubwise56/Dubs-Mint-Menus#5]
https://github.com/KiameV/rimworld-modifyresearchtime/issues/3#issue-860509683 

See linked issue on Change Research Speed for details

**Comment by Dubwise56** [comment]
problem is with their mod finishing research during load combined with my mod needing to get settings on demand because of compatability with another mod but i put in workaround in the next update for it
