### ISSUE TITLE
[1.0] No recipe lists, no UI changes

### ISSUE THREAD

**Issue by McChickn** [Dubwise56/Dubs-Mint-Menus#7]
It seemed to me like I had the same problem as the guy who posted to reddit a year ago:
https://www.reddit.com/r/RimWorld/comments/h0t2t3/problems_with_dubs_mint_menus_playing_10/

Even with a new game, with only Core and Mint Menus, I saw none of the changes I should see, and clicking "Bills" button on any workbench just gave me a small black bar next to that button, so I didn't even see the vanilla recipe list to add anything to the workbench queue. That really confused me for a while. I thought something was broken, I even installed older versions from the time before 1.1, to see if that might help. (It didn't.)

But unlike that guy, I had access to the mod settings, which showed me what was wrong: All values defaulted to off or zero. Zero width, zero height, of course I couldn't see anything.

I recommend adding better default values for people installing the first time,

**Comment by Dubwise56** [comment]
the default values are all correct, its a problem with the game itself, basically nothing i can do about it because the game corrupts the mod settings xml, update to the latest version of rimworld, i haven't had the bug reported in a long time

**Comment by McChickn** [comment]
Nvm then, if it can't be done. It's easy enough to deal with once you know about it.
Sorry if it was reported before.
1.0.2559 is already the latest 1.0 version afaik.

**Comment by Dubwise56** [comment]
i mean 1.3, there's a large number of bug fixes since 1.0
